[default]
DEBUG = true
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'
TITLE = "myFlaskApi"
JWT_SECRET_KEY = 'my-secret-key'
JWT_ACCESS_TOKEN_EXPIRES = 604800 #one week in seconds
EXTENSIONS = [
    "myFlaskApi.database.database:init_app",
    "myFlaskApi.ext.auth:init_app",
    "myFlaskApi.ext.commands:init_app",
    "myFlaskApi.restapi:init_app",
]

[development]
SQLALCHEMY_DATABASE_URI = 'sqlite:///development.db'

[production]
SQLALCHEMY_DATABASE_URI = 'sqlite:///production.db'

# .env
# FLASK_ENV=development
# FLASK_APP=myFlaskApi.app:create_app